// GENERATED by scripts/fonts.mjs — do not edit. Run `pnpm fonts` instead.

/** A bundled family, as the font pickers offer it. `value` is the CSS
 *  font-family list a theme stores. */
export interface BundledFont {
  label: string;
  role: "serif" | "sans" | "mono";
  value: string;
}

export const BUNDLED_FONTS: BundledFont[] = [
  { label: "Source Serif 4", role: "serif", value: '"Source Serif 4 Variable", Georgia, serif' },
  { label: "Literata", role: "serif", value: '"Literata Variable", Georgia, serif' },
  { label: "Newsreader", role: "serif", value: '"Newsreader Variable", Georgia, serif' },
  { label: "EB Garamond", role: "serif", value: '"EB Garamond Variable", Georgia, serif' },
  { label: "Crimson Pro", role: "serif", value: '"Crimson Pro Variable", Georgia, serif' },
  { label: "Lora", role: "serif", value: '"Lora Variable", Georgia, serif' },
  { label: "Faustina", role: "serif", value: '"Faustina Variable", Georgia, serif' },
  { label: "Alegreya", role: "serif", value: '"Alegreya Variable", Georgia, serif' },
  { label: "Bitter", role: "serif", value: '"Bitter Variable", Georgia, serif' },
  { label: "Fraunces", role: "serif", value: '"Fraunces Variable", Georgia, serif' },
  { label: "IBM Plex Serif", role: "serif", value: '"IBM Plex Serif", Georgia, serif' },
  { label: "Inter", role: "sans", value: '"Inter Variable", system-ui, sans-serif' },
  { label: "Inter Tight", role: "sans", value: '"Inter Tight Variable", system-ui, sans-serif' },
  { label: "Geist", role: "sans", value: '"Geist Variable", system-ui, sans-serif' },
  { label: "Public Sans", role: "sans", value: '"Public Sans Variable", system-ui, sans-serif' },
  {
    label: "Schibsted Grotesk",
    role: "sans",
    value: '"Schibsted Grotesk Variable", system-ui, sans-serif',
  },
  { label: "Figtree", role: "sans", value: '"Figtree Variable", system-ui, sans-serif' },
  {
    label: "Space Grotesk",
    role: "sans",
    value: '"Space Grotesk Variable", system-ui, sans-serif',
  },
  {
    label: "Source Sans 3",
    role: "sans",
    value: '"Source Sans 3 Variable", system-ui, sans-serif',
  },
  { label: "IBM Plex Sans", role: "sans", value: '"IBM Plex Sans", system-ui, sans-serif' },
  {
    label: "Atkinson Hyperlegible",
    role: "sans",
    value: '"Atkinson Hyperlegible Next Variable", system-ui, sans-serif',
  },
  {
    label: "JetBrains Mono",
    role: "mono",
    value: '"JetBrains Mono Variable", ui-monospace, monospace',
  },
  { label: "Geist Mono", role: "mono", value: '"Geist Mono Variable", ui-monospace, monospace' },
  { label: "Fira Code", role: "mono", value: '"Fira Code Variable", ui-monospace, monospace' },
  {
    label: "Source Code Pro",
    role: "mono",
    value: '"Source Code Pro Variable", ui-monospace, monospace',
  },
  { label: "IBM Plex Mono", role: "mono", value: '"IBM Plex Mono", ui-monospace, monospace' },
];
